### ISSUE TITLE
Environment variable to configure database table prefix

### ISSUE THREAD

**Issue by FJEANNOT** [bitnami/bitnami-docker-prestashop#103]
**Description**

Could it be possible to add an environment variable to the container in order to change the default table prefix (defined in app/config/parameters.php `'database_prefix' => 'ps_'`). Like $DATABASE_PREFIX="ps_"

**Comment by alemorcuq** [comment]
Hi, @FJEANNOT.

Yes, it should be easy to support as we are doing a command line installation (https://github.com/bitnami/bitnami-docker-prestashop/blob/483604cfff0560295e3deb05f6b925eb1d34d159/1.7/debian-10/rootfs/opt/bitnami/scripts/libprestashop.sh#L111) and according to the documentation you can set it with the `--prefix` flag: https://doc.prestashop.com/display/PS17/Installing+PrestaShop+using+the+command-line+script

Would you be interested in contributing with a PR? Otherwise I can create an internal task to add support for it.

**Comment by FJEANNOT** [comment]
Yes i would definetely be interested! I will start to work on this in a few days

**Comment by FJEANNOT** [comment]
Solved by #104
