### ISSUE TITLE
Permission denied for symbolic links 

### ISSUE THREAD

**Issue by BartoszCoyote** [bitnami/bitnami-docker-prestashop#106]
I extend bitnami prestashop image by adding `update-ca-certificates` line to /opt/bitnami/scripts/prestashop/entrypoint.sh script.

But when starting the container I got a problem.

2021-06-08 10:04:15.888 CEST
Updating certificates in /etc/ssl/certs...
Error
2021-06-08 10:04:16.648 CEST
ln: failed to create symbolic link '/etc/ssl/certs/cert.pem': Permission denied

what can I do about it?
Thanks for help

**Comment by carrodher** [comment]
Hi, the bitnami/prestashop container image is a non-root container, this is a security best practice but it introduces some limitations; you can find more information in [this blog post](https://docs.bitnami.com/tutorials/bitnami-best-practices-hardening-containers#root-and-non-root-containers).

You can change the user at build time by removing the `USER 1001` directive from the _Dockerfile_, in this way the image is going to be built using `root`. If you already have the image built and you are deploying it using docker-compose, you can add the `user: root` parameter in the _docker-compose.yaml_ after the `image:` field in order to modify the user at runtime. In Kubernetes, the user that executes the container can be customized by using [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).

**Comment by BartoszCoyote** [comment]
@carrodher Thanks, works.

But I have another question. 
My db provider required a ca certificate for db connection.
How can I atach to presta my cert file and run shop with secured db connection?
