### ISSUE TITLE
Bitnami prestashop image upgrade

### ISSUE THREAD

**Issue by babyfooter** [bitnami/bitnami-docker-prestashop#60]
Hi guys,

I have a question about your upgrade process for Prestashop image. Reading your instructions, 

```
 - Remove the currently running container
      For docker-compose: $ docker-compose rm -v prestashop
 -     Run the new image
      For docker-compose: $ docker-compose start prestashop
```

Seems that you can't start prestashop image as you just remove it. Could you pls add missing step?

**Comment by babyfooter** [comment]
Wow, I just try to update my docker-compose file with image: 'bitnami/prestashop:1.7' and get following error trying to mount new docker image (docker-compose up -d)

```
prestashop_1  | nami    INFO  Initializing prestashop
prestashop_1  | Error executing 'postInstallation': Unable to start com.bitnami.apache: httpd: Syntax error on line 157 of /opt/bitnami/apache/conf/httpd.conf: Cannot load modules/libphp5.so into server: /opt/bitnami/apache/modules/libphp5.so: cannot open shared object file: No such file or directory
prestashop_1  | : httpd: Syntax error on line 157 of /opt/bitnami/apache/conf/httpd.conf: Cannot load modules/libphp5.so into server: /opt/bitnami/apache/modules/libphp5.so: cannot open shared object file: No such file or directory
```

Could you help me? Thx

**Comment by juan131** [comment]
Hello @babyfooter 

Regarding the first issue you mentioned, you're right! There's a wrong step. I updated the section and it will be updated once a new version/revision of the Docker Image is released. Thanks for reporting it. Basically you need to run `docker-compose run prestashop` instead of `docker-compose start prestashop`.

Regarding the second issue, could you please detail the steps you follow in order to upgrade your Bitnami PrestaShop Container?
