### ISSUE TITLE
Administrator Folder

### ISSUE THREAD

**Issue by 4mon** [bitnami/bitnami-docker-prestashop#85]
How can I change the name of the administration folder?
I can't find any environment variable

**Comment by miguelaeh** [comment]
Hi @4mon,
Could you elaborate what do you mean with administrator folder? Could you post a link to the docs or something?

**Comment by 4mon** [comment]
Hi @miguelaeh, what I mean is how to change the name of the administrator folder (url / administrator) to maximize security. By default the prestashop installation changes the name of the (random) folder to ensure the url of the backend. I hope I have been clearer. Thank you so much.
Saludos!

**Comment by miguelaeh** [comment]
Hi @4mon ,
Now I understand, there is no way to do that in the container, but I have been testing it and you can create your own image extending from our image.
About how to do that, I have tested that if you exec into the container, rename the `administration` folder to whatever you want in the URL and restart Apache (I did it with `https -k restart`) then, you can access your administrator panel using `/<folder-name` instead of `/administrator`. So I recommend you to extend our image and perform those steps.
I hope this is helpful, please don't hesitate in ask again if you have doubts.
Regards.

**Comment by 4mon** [comment]
Thanks so much Miguel! Cheers!

**Comment by 4mon** [comment]
@miguelaeh ! 
Another more primitive option (and at hand):
with "docker volume inspect" I see that the data is hosted in "/ var / lib / docker / volumes / ubuntu_prestashop_data / _data"
I just change the name and voila !! works!
It remains only to make a script in python or bash to automate the renaming of the directory by the desired one.
ps: before you have to stop the containers.
Greetings.

**Comment by miguelaeh** [comment]
Thank you very much for sharing more solutions for other users!
