### ISSUE TITLE
Why am I being redirected to prestashop.example.com ?

### ISSUE THREAD

**Issue by MrCoffey** [bitnami/bitnami-docker-prestashop#9]
Hi guys!

Once I finish the setup with docker, and try to access to prestashop I am being redirected to prestashop.example.com.

In the first attempt I was using this docker-compose file https://github.com/bitnami/bitnami-docker-prestashop/blob/master/docker-compose.yml. 

I tried changing `PRESTASHOP_HOST=prestashop.example.com`  to `PRESTASHOP_HOST=localhost`, but it still redirecting to the same host. Did I miss something?

My logs looks like:
```
mariadb_1      | 2016-09-08 21:20:06 139827294975936 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.29-76.2 started; log sequence number 10599416
mariadb_1      | 2016-09-08 21:20:06 139826724595456 [Note] InnoDB: Dumping buffer pool(s) not yet started
mariadb_1      | 2016-09-08 21:20:06 139827294975936 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1      | 2016-09-08 21:20:06 139827294975936 [Note] Recovering after a crash using tc.log
mariadb_1      | 2016-09-08 21:20:06 139827294975936 [Note] Starting crash recovery...
mariadb_1      | 2016-09-08 21:20:06 139827294975936 [Note] Crash recovery finished.
mariadb_1      | 2016-09-08 21:20:06 139827294975936 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1      | 2016-09-08 21:20:06 139827294975936 [Warning] 'proxies_priv' entry '@% root@a403db337372' ignored in --skip-name-resolve mode.
mariadb_1      | 2016-09-08 21:20:06 139827294975936 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1      | Version: '10.1.14-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
application_1  | 172.20.0.1 - - [08/Sep/2016:21:14:40 +0000] "GET / HTTP/1.1" 302 -
application_1  | 172.20.0.1 - - [08/Sep/2016:21:14:40 +0000] "GET / HTTP/1.1" 302 -
application_1  | 172.20.0.1 - - [08/Sep/2016:21:27:35 +0000] "GET / HTTP/1.1" 302 -
application_1  | 172.20.0.1 - - [08/Sep/2016:21:27:36 +0000] "GET / HTTP/1.1" 302 -
```

My Docker version is 1.12.1, build 23cf638
My docker-compose version 1.8.0, build f3628c7
Running on debian 8.5

**Comment by dgonzalezruiz** [comment]
Hi Mrcoffey!

We are sorry that you ran into this issue. We persist the configuration and modified data of the applications created in volumes, so that whenever you stop those containers and restart them, everything will be the same (photos uploaded, products created, accounts...). When the containers are restarted (services within docker-compose), that configuration is not modified nor recreated. It's just used by the application again. 

What happened to you is that you first ran docker-compose with that sample domain. That domain was persisted in a volume, so that whenever you restart the containers the same host is going to be used. (even if that variable is modified) 
You have several options from here:
- You could delete volumes attached (and the `PRESTASHOP_HOST` variable within `docker-compose.yml`) so that the application is created from scratch and the domain is correctly set. I don't recommend this option!
- You can use the `configureHost` method. Just execute `docker-compose exec application nami execute prestashop configureHost localhost`. Have in mind that in order to use this, you'll have to wait until the pull request I just opened is merged (it should be merged today).

Let me know if you have any other doubt!

**Comment by chipironcin** [comment]
Just a few comments more:
  - PR is #10
  - To delete volumes associated to your Prestashop compose up, use the following command

     ```
     docker-compose down
     docker volume ls | grep "prestashop" | awk '{print $2}' | xargs docker volume rm $1
     ```
  - If you don't specify a `PRESTASHOP_HOST` it will default to the machine IP running the containers
  - The best option is to run `configureHost` function that @dgonzalezruiz mentioned, once your compose is up and running (wait for the application to start before calling the function)

**Comment by MrCoffey** [comment]
FIXED!

Thank you guys for your amazing work!
