### ISSUE TITLE
[feature-request] Secure communication with the Database

### ISSUE THREAD

**Issue by rcaillon-Iliad** [bitnami/bitnami-docker-prestashop#98]
Hello,
Would it be possible to implement secure communication (TLS) between the Prestashop container and a remote database? This is not an out of the box feature of Prestashop, but it would be great to have it implemented in the Bitnami image.

Thank you!

**Comment by carrodher** [comment]
It seems this is already implemented by using the `MYSQL_CLIENT_TLS_ENABLED` environment variable but probably there is a lack of documentation. Can you try in your environment by setting this env. variable to `yes`: `MYSQL_CLIENT_TLS_ENABLED=yes`.

In that case, the mysql-client binary is executed with the `--ssl` flag enabled:

https://github.com/bitnami/bitnami-docker-prestashop/blob/ff0a1ea8de419c7e01c9b682e67ba66810bba793/1.7/debian-10/rootfs/opt/bitnami/scripts/libmysqlclient.sh#L131

**Comment by rcaillon-Iliad** [comment]
I didn't know about this variable, good to know! But does Prestashop execute its SQL queries through the mysql-client binary?

**Comment by rcaillon-Iliad** [comment]
An other thing: My database uses a certificate signed by a custom CA, I'd like to be able to validate the certificate.
Would it be possible to support some other mysql options? At least `ssl-ca` and `ssl-verify-server-cert`

**Comment by carrodher** [comment]
> But does Prestashop execute its SQL queries through the mysql-client binary?

Not sure how PrestaShop (as an application, not the container) internally works. In this case, the mentioned env. variable is set to use TLS during the communication required to the container initialization logic.

> My database uses a certificate signed by a custom CA, I'd like to be able to validate the certificate.
Would it be possible to support some other mysql options? At least ssl-ca and ssl-verify-server-cert

We are open to supporting new features in the containers and Helm Charts, as the code is publicly available in GitHub, external contributions are welcome and the team will be happy to review them and provide feedback. Another solution is to create an internal task on our side in order to evaluate and implement the new features, but this path depends on the capacity of the team, and usually task to fix issues are on top of the new features additions so in that case, I can't guarantee an ETA for this kind of task. Do you think it could be something you could contribute?
